// Type Imports
// import type { ECommerceType } from '@/types/apps/ecommerceTypes'

export const db = {
  products: [
    {
      id: 1,
      productName: 'OP & D Companies',
      category: 'Shrink Caps',
      stock: true,
      sku: 19472,
      price: 'GH₵99',
      qty: 665,
      status: 'Stores',
      image: '/images/apps/ecommerce/shrink-cap1.jpeg',
      productBrand: 'Super XDR shrink caps'
    },
    {
      id: 2,
      productName: 'Echo Dot Sachet Water Rolls',
      category: 'Sachet Water Rolls',
      stock: false,
      sku: 72836,
      price: 'GH₵5.50',
      qty: 827,
      status: 'Production',
      image: '/images/apps/ecommerce/purewaterrolls.jpeg',
      productBrand: 'Echo Dot sachet water rolls'
    },
    {
      id: 3,
      productName: 'Dohioue Heat Shrink Cap',
      category: 'Heat Shrink Caps',
      stock: false,
      sku: 29540,
      price: 'GH₵6.34',
      qty: 804,
      status: 'Production',
      image: '/images/apps/ecommerce/heat-shrink-cap2.jpeg',
      productBrand: '2 inch heat shrink cap'
    },
    {
      id: 4,
      productName: 'Dohioue Labels',
      category: 'Labels',
      stock: false,
      sku: 29540,
      price: 'GH₵64.34',
      qty: 804,
      status: 'Warehouse',
      image: '/images/apps/ecommerce/water-label1.jpg',
      productBrand: 'Large label 3 inch wide'
    },
  ],
  reviews: [
    {
      id: 1,
      product: 'iPhone 14 Pro',
      companyName: 'Super Retina XDR display footnote Pro Motion technology',
      productImage: '/images/apps/ecommerce/product-1.png',
      requisitionist: 'Zane Scraggs',
      email: 'zscraggs0@flavors.me',
      avatar: '/images/avatars/1.png',
      date: '5/28/2020',
      status: 'Approved',
      review: 2,
      head: 'lorem ipsum dolor',
      para: 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.'
    },
    {
      id: 2,
      product: 'Echo Dot (4th Gen)',
      companyName: 'Echo Dot Smart speaker with Alexa',
      productImage: '/images/apps/ecommerce/product-2.png',
      requisitionist: 'Stacey Hallgalley',
      email: 'shallgalley1@google.nl',
      avatar: '/images/avatars/2.png',
      date: '3/21/2021',
      status: 'Approved',
      review: 5,
      head: 'libero ut',
      para: 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.'
    },
    {
      id: 3,
      product: 'Dohioue Wall Clock',
      companyName: 'Modern 10 Inch Battery Operated Wall Clocks',
      productImage: '/images/apps/ecommerce/product-3.png',
      requisitionist: 'Francyne Coulthurst',
      email: 'fcoulthurst2@upenn.edu',
      avatar: '/images/avatars/3.png',
      date: '8/10/2020',
      status: 'Approved',
      review: 2,
      head: 'neque libero convallis',
      para: 'Phasellus in felis. Donec semper sapien a libero. Nam dui.'
    },
    {
      id: 4,
      product: 'INZCOU Running Shoes',
      companyName: 'Lightweight Tennis Shoes Non Slip Gym Workout Shoes',
      productImage: '/images/apps/ecommerce/product-4.png',
      requisitionist: 'Nate De Mitris',
      email: 'nde3@intel.com',
      avatar: '/images/avatars/4.png',
      date: '12/18/2021',
      status: 'Pending',
      review: 3,
      head: 'accumsan tellus nisi eu',
      para: 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.'
    },
    {
      id: 5,
      product: 'Apple Watch Series 7',
      companyName: 'Starlight Aluminum Case with Starlight Sport Band.',
      productImage: '/images/apps/ecommerce/product-5.png',
      requisitionist: 'Ethel Zanardii',
      email: 'ezanardii4@mapy.cz',
      avatar: '/images/avatars/5.png',
      date: '6/12/2020',
      status: 'Pending',
      review: 1,
      head: 'etiam faucibus cursus',
      para: 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.'
    },
    {
      id: 6,
      product: 'Meta Quest 2',
      companyName: 'Advanced All-In-One Virtual Reality Headset',
      productImage: '/images/apps/ecommerce/product-6.png',
      requisitionist: 'Fancy Tweedell',
      email: 'ftweedell5@telegraph.co.uk',
      avatar: '/images/avatars/6.png',
      date: '11/23/2020',
      status: 'Pending',
      review: 1,
      head: 'in faucibus orci luctus et',
      para: 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.'
    },
    {
      id: 7,
      product: 'MacBook Pro 16',
      companyName: 'Laptop M2 Pro chip with 12‑core CPU and 19‑core GPU',
      productImage: '/images/apps/ecommerce/product-7.png',
      requisitionist: 'Abeu Gregorace',
      email: 'agregorace6@godaddy.com',
      avatar: '/images/avatars/7.png',
      date: '9/8/2020',
      status: 'Pending',
      review: 2,
      head: 'vel enim',
      para: 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.'
    },
    {
      id: 8,
      product: 'SAMSUNG Galaxy S22 Ultra',
      companyName: 'Android Smartphone, 256GB, 8K Camera',
      productImage: '/images/apps/ecommerce/product-8.png',
      requisitionist: 'Sibylle Goodacre',
      email: 'sgoodacre7@washingtonpost.com',
      avatar: '/images/avatars/8.png',
      date: '6/10/2021',
      status: 'Pending',
      review: 1,
      head: 'eget semper rutrum',
      para: 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.'
    },
    {
      id: 9,
      product: 'Air Jordan',
      companyName: 'Air Jordan is a line of basketball shoes produced by Nike',
      productImage: '/images/apps/ecommerce/product-9.png',
      requisitionist: 'Gisela Leppard',
      email: 'gleppard8@yandex.ru',
      avatar: '/images/avatars/1.png',
      date: '4/20/2020',
      status: 'Approved',
      review: 2,
      head: 'ut mauris',
      para: 'Fusce consequat. Nulla nisl. Nunc nisl.'
    },
    {
      id: 10,
      product: 'VISKABACKA',
      companyName: 'Armchair, Skartofta black/light grey',
      productImage: '/images/apps/ecommerce/product-10.png',
      requisitionist: 'Hilario Wheldon',
      email: 'hwheldon9@apple.com',
      avatar: '/images/avatars/2.png',
      date: '8/21/2020',
      status: 'Pending',
      review: 2,
      head: 'amet consectetuer adipiscing elit proin',
      para: 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.'
    },
    {
      id: 11,
      product: 'Nintendo Switch',
      companyName: 'TV Mode, Tabletop Mode, Handheld Mode',
      productImage: '/images/apps/ecommerce/product-11.png',
      requisitionist: 'Ivie McGlaughn',
      email: 'imcglaughna@mapquest.com',
      avatar: '/images/avatars/3.png',
      date: '4/13/2020',
      status: 'Pending',
      review: 4,
      head: 'eget nunc donec',
      para: 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.'
    },
    {
      id: 12,
      product: 'PlayStation 5',
      companyName: 'Marvel at incredible graphics and experience',
      productImage: '/images/apps/ecommerce/product-12.png',
      requisitionist: 'Neel Kingscott',
      email: 'nkingscottb@soup.io',
      avatar: '/images/avatars/4.png',
      date: '12/27/2020',
      status: 'Approved',
      review: 1,
      head: 'lacus at velit',
      para: 'Phasellus in felis. Donec semper sapien a libero. Nam dui.'
    },
    {
      id: 13,
      product: 'Amazon Fire TV',
      companyName: '4K UHD smart TV, stream live TV without cable',
      productImage: '/images/apps/ecommerce/product-13.png',
      requisitionist: 'Tracey Ventham',
      email: 'tventhamc@thetimes.co.uk',
      avatar: '/images/avatars/5.png',
      date: '3/17/2021',
      status: 'Approved',
      review: 3,
      head: 'at nunc commodo placerat praesent',
      para: 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.'
    },
    {
      id: 14,
      product: 'Smiletag Ceramic Vase',
      companyName: 'Modern Farmhouse Decor Vase Set of 3',
      productImage: '/images/apps/ecommerce/product-14.png',
      requisitionist: 'Rollo Truckell',
      email: 'rtruckelld@gravatar.com',
      avatar: '/images/avatars/6.png',
      date: '2/23/2020',
      status: 'Approved',
      review: 5,
      head: 'in hac',
      para: 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.'
    },
    {
      id: 15,
      product: 'Apple iPad',
      companyName: '10.2-inch Retina Display, 64GB',
      productImage: '/images/apps/ecommerce/product-15.png',
      requisitionist: 'Jabez Heggs',
      email: 'jheggse@nba.com',
      avatar: '/images/avatars/7.png',
      date: '4/21/2020',
      status: 'Approved',
      review: 1,
      head: 'ac consequat',
      para: 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.'
    },
    {
      id: 16,
      product: 'BANGE Anti Theft Backpack',
      companyName: 'Smart Business Laptop Fits 15.6 Inch Notebook',
      productImage: '/images/apps/ecommerce/product-16.png',
      requisitionist: 'Micaela Rowesby',
      email: 'mrowesbyf@surveymonkey.com',
      avatar: '/images/avatars/1.png',
      date: '12/11/2021',
      status: 'Approved',
      review: 1,
      head: 'mattis egestas metus',
      para: 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.'
    },
  ],
  referrals: [
    {
      id: 1,
      user: 'Koressa Leyfield',
      email: 'kleyfield0@columbia.edu',
      avatar: '/images/avatars/1.png',
      referredId: 3398,
      status: 'Unpaid',
      value: 'GH₵655.92',
      earning: 'GH₵80.17'
    },
    {
      id: 2,
      user: 'Tania Brotherhood',
      email: 'tbrotherhood1@bing.com',
      avatar: '/images/avatars/5.png',
      referredId: 6740,
      status: 'Unpaid',
      value: 'GH₵113.04',
      earning: 'GH₵16.72'
    },
    {
      id: 3,
      user: 'Clemmie Montgomery',
      email: 'cmontgomery2@fema.gov',
      avatar: '/images/avatars/1.png',
      referredId: 2749,
      status: 'Unpaid',
      value: 'GH₵717.09',
      earning: 'GH₵99.02'
    },
    {
      id: 4,
      user: 'Job Jope',
      email: 'jjope3@istockphoto.com',
      avatar: '/images/avatars/7.png',
      referredId: 1413,
      status: 'Paid',
      value: 'GH₵465.13',
      earning: 'GH₵8.23'
    },
    {
      id: 5,
      user: 'Christoffer Derell',
      email: 'cderell4@apple.com',
      avatar: '/images/avatars/1.png',
      referredId: 9176,
      status: 'Paid',
      value: 'GH₵202.81',
      earning: 'GH₵82.51'
    },
    {
      id: 6,
      user: 'Herminia Eyree',
      email: 'heyree5@gizmodo.com',
      avatar: '/images/avatars/8.png',
      referredId: 6975,
      status: 'Unpaid',
      value: 'GH₵802.40',
      earning: 'GH₵19.52'
    },
    {
      id: 7,
      user: 'Dela Lathwell',
      email: 'dlathwell6@webmd.com',
      avatar: '/images/avatars/1.png',
      referredId: 4552,
      status: 'Paid',
      value: 'GH₵470.46',
      earning: 'GH₵31.45'
    },
    {
      id: 8,
      user: 'Kirbie Greenhow',
      email: 'kgreenhow7@sina.com.cn',
      avatar: '/images/avatars/1.png',
      referredId: 4131,
      status: 'Unpaid',
      value: 'GH₵199.28',
      earning: 'GH₵56.00'
    },
    {
      id: 9,
      user: 'Adrienne Tourne',
      email: 'atourne8@fotki.com',
      avatar: '/images/avatars/1.png',
      referredId: 4072,
      status: 'Unpaid',
      value: 'GH₵774.33',
      earning: 'GH₵21.78'
    },
    {
      id: 10,
      user: 'Vanya Hearons',
      email: 'vhearons9@blogspot.com',
      avatar: '/images/avatars/1.png',
      referredId: 3070,
      status: 'Unpaid',
      value: 'GH₵067.14',
      earning: 'GH₵04.91'
    },
    {
      id: 11,
      user: 'Garnette Abramcik',
      email: 'gabramcika@google.com',
      avatar: '/images/avatars/3.png',
      referredId: 7828,
      status: 'Unpaid',
      value: 'GH₵375.10',
      earning: 'GH₵47.01'
    },
    {
      id: 12,
      user: 'Akim Korba',
      email: 'akorbab@flickr.com',
      avatar: '/images/avatars/3.png',
      referredId: 8561,
      status: 'Unpaid',
      value: 'GH₵104.91',
      earning: 'GH₵52.75'
    },
    {
      id: 13,
      user: 'Cull Scipsey',
      email: 'cscipseyc@adobe.com',
      avatar: '/images/avatars/2.png',
      referredId: 9287,
      status: 'Paid',
      value: 'GH₵375.13',
      earning: 'GH₵90.75'
    },
    {
      id: 14,
      user: 'Anabal Hakking',
      email: 'ahakkingd@paginegialle.it',
      avatar: '/images/avatars/7.png',
      referredId: 4892,
      status: 'Paid',
      value: 'GH₵797.12',
      earning: 'GH₵79.71'
    },
    {
      id: 15,
      user: 'Linzy Swiers',
      email: 'lswierse@flickr.com',
      avatar: '/images/avatars/5.png',
      referredId: 9180,
      status: 'Unpaid',
      value: 'GH₵996.63',
      earning: 'GH₵10.27'
    },
    {
      id: 16,
      user: 'Willy Espinet',
      email: 'wespinetf@addtoany.com',
      avatar: '/images/avatars/1.png',
      referredId: 9102,
      status: 'Paid',
      value: 'GH₵048.18',
      earning: 'GH₵69.06'
    },
    {
      id: 17,
      user: 'Carter Gommowe',
      email: 'cgommoweg@purevolume.com',
      avatar: '/images/avatars/1.png',
      referredId: 7049,
      status: 'Unpaid',
      value: 'GH₵049.95',
      earning: 'GH₵42.78'
    },
    {
      id: 18,
      user: 'Andre Kenway',
      email: 'akenwayh@rambler.ru',
      avatar: '/images/avatars/6.png',
      referredId: 9826,
      status: 'Paid',
      value: 'GH₵221.71',
      earning: 'GH₵47.19'
    },
    {
      id: 19,
      user: 'Quintina Endacott',
      email: 'qendacotti@answers.com',
      avatar: '/images/avatars/1.png',
      referredId: 4555,
      status: 'Paid',
      value: 'GH₵918.70',
      earning: 'GH₵43.44'
    },
    {
      id: 20,
      user: 'Shurwood Cabble',
      email: 'scabblej@twitpic.com',
      avatar: '/images/avatars/4.png',
      referredId: 5591,
      status: 'Paid',
      value: 'GH₵073.50',
      earning: 'GH₵80.62'
    },
    {
      id: 21,
      user: 'Thatch Borchardt',
      email: 'tborchardtk@bing.com',
      avatar: '/images/avatars/1.png',
      referredId: 4491,
      status: 'Unpaid',
      value: 'GH₵389.56',
      earning: 'GH₵46.81'
    },
    {
      id: 22,
      user: "Fawne O'Scanlan",
      email: 'foscanlanl@europa.eu',
      avatar: '/images/avatars/8.png',
      referredId: 2946,
      status: 'Paid',
      value: 'GH₵471.34',
      earning: 'GH₵47.24'
    },
    {
      id: 23,
      user: 'Ode Birts',
      email: 'obirtsm@sphinn.com',
      avatar: '/images/avatars/2.png',
      referredId: 2328,
      status: 'Paid',
      value: 'GH₵484.83',
      earning: 'GH₵15.79'
    },
    {
      id: 24,
      user: 'Bella Michelle',
      email: 'bmichellen@npr.org',
      avatar: '/images/avatars/2.png',
      referredId: 5725,
      status: 'Paid',
      value: 'GH₵088.56',
      earning: 'GH₵29.64'
    },
    {
      id: 25,
      user: 'Aurora Skpsey',
      email: 'askpseyo@cdc.gov',
      avatar: '/images/avatars/6.png',
      referredId: 2821,
      status: 'Unpaid',
      value: 'GH₵938.87',
      earning: 'GH₵17.42'
    },
    {
      id: 26,
      user: 'Neddie Maunders',
      email: 'nmaundersp@blogspot.com',
      avatar: '/images/avatars/7.png',
      referredId: 1661,
      status: 'Unpaid',
      value: 'GH₵256.70',
      earning: 'GH₵21.01'
    },
    {
      id: 27,
      user: 'Andria Chisnell',
      email: 'achisnellq@imageshack.us',
      avatar: '/images/avatars/4.png',
      referredId: 3363,
      status: 'Unpaid',
      value: 'GH₵106.99',
      earning: 'GH₵05.15'
    },
    {
      id: 28,
      user: 'Reggy Arnao',
      email: 'rarnaor@kickstarter.com',
      avatar: '/images/avatars/3.png',
      referredId: 7814,
      status: 'Rejected',
      value: 'GH₵300.60',
      earning: 'GH₵34.28'
    },
    {
      id: 29,
      user: 'Shaylah Hasselby',
      email: 'shasselbys@odnoklassniki.ru',
      avatar: '/images/avatars/4.png',
      referredId: 8324,
      status: 'Paid',
      value: 'GH₵874.21',
      earning: 'GH₵99.72'
    },
    {
      id: 30,
      user: 'Althea Dayce',
      email: 'adaycet@youtu.be',
      avatar: '/images/avatars/8.png',
      referredId: 6069,
      status: 'Paid',
      value: 'GH₵098.09',
      earning: 'GH₵69.32'
    },
    {
      id: 31,
      user: 'Hector Biaggioli',
      email: 'hbiaggioliu@umich.edu',
      avatar: '/images/avatars/5.png',
      referredId: 5286,
      status: 'Paid',
      value: 'GH₵752.66',
      earning: 'GH₵46.63'
    },
    {
      id: 32,
      user: 'Mycah Gotcher',
      email: 'mgotcherv@yellowbook.com',
      avatar: '/images/avatars/1.png',
      referredId: 7944,
      status: 'Unpaid',
      value: 'GH₵959.05',
      earning: 'GH₵88.10'
    },
    {
      id: 33,
      user: 'Garv Scruton',
      email: 'gscrutonw@sun.com',
      avatar: '/images/avatars/5.png',
      referredId: 6876,
      status: 'Unpaid',
      value: 'GH₵588.37',
      earning: 'GH₵80.51'
    },
    {
      id: 34,
      user: 'Renell Gurnett',
      email: 'rgurnettx@businessweek.com',
      avatar: '/images/avatars/2.png',
      referredId: 7802,
      status: 'Rejected',
      value: 'GH₵542.30',
      earning: 'GH₵08.96'
    },
    {
      id: 35,
      user: 'Toinette Kilgrew',
      email: 'tkilgrewy@wikispaces.com',
      avatar: '/images/avatars/7.png',
      referredId: 6946,
      status: 'Paid',
      value: 'GH₵447.48',
      earning: 'GH₵10.48'
    },
    {
      id: 36,
      user: 'Corinne Cockshtt',
      email: 'ccockshttz@house.gov',
      avatar: '/images/avatars/7.png',
      referredId: 1372,
      status: 'Paid',
      value: 'GH₵700.16',
      earning: 'GH₵58.94'
    },
    {
      id: 37,
      user: 'Isis Yurkiewicz',
      email: 'iyurkiewicz10@addthis.com',
      avatar: '/images/avatars/4.png',
      referredId: 2384,
      status: 'Unpaid',
      value: 'GH₵456.86',
      earning: 'GH₵80.52'
    },
    {
      id: 38,
      user: 'Gerianna Nott',
      email: 'gnott11@youtu.be',
      avatar: '/images/avatars/5.png',
      referredId: 1971,
      status: 'Paid',
      value: 'GH₵563.94',
      earning: 'GH₵15.34'
    },
    {
      id: 39,
      user: 'Calli Mewes',
      email: 'cmewes12@mit.edu',
      avatar: '/images/avatars/5.png',
      referredId: 7323,
      status: 'Unpaid',
      value: 'GH₵400.29',
      earning: 'GH₵67.44'
    },
    {
      id: 40,
      user: 'Sonnnie Keeltagh',
      email: 'skeeltagh13@typepad.com',
      avatar: '/images/avatars/7.png',
      referredId: 5719,
      status: 'Paid',
      value: 'GH₵977.34',
      earning: 'GH₵52.01'
    },
    {
      id: 41,
      user: 'Penelope Hause',
      email: 'phause14@netlog.com',
      avatar: '/images/avatars/3.png',
      referredId: 9347,
      status: 'Paid',
      value: 'GH₵155.12',
      earning: 'GH₵01.49'
    },
    {
      id: 42,
      user: 'Dannie Romeo',
      email: 'dromeo15@ask.com',
      avatar: '/images/avatars/1.png',
      referredId: 1559,
      status: 'Rejected',
      value: 'GH₵110.30',
      earning: 'GH₵5.40'
    },
    {
      id: 43,
      user: 'Keely Giannazzi',
      email: 'kgiannazzi16@mit.edu',
      avatar: '/images/avatars/8.png',
      referredId: 3307,
      status: 'Paid',
      value: 'GH₵178.00',
      earning: 'GH₵73.10'
    },
    {
      id: 44,
      user: 'Kassia Mottini',
      email: 'kmottini17@Ghana.gov',
      avatar: '/images/avatars/7.png',
      referredId: 4426,
      status: 'Rejected',
      value: 'GH₵921.60',
      earning: 'GH₵65.93'
    },
    {
      id: 45,
      user: 'Burr Scrauniage',
      email: 'bscrauniage18@wunderground.com',
      avatar: '/images/avatars/8.png',
      referredId: 3570,
      status: 'Paid',
      value: 'GH₵891.09',
      earning: 'GH₵00.25'
    }
  ],
  orderData: [
    {
      id: 1,
      order: '5434',
      customer: 'Gabrielle Feyer',
      email: 'gfeyer0@nyu.edu',
      avatar: '/images/avatars/8.png',
      payment: 1,
      status: 'Delivered',
      spent: 73.98,
      method: 'paypalLogo',
      date: '5/16/2022',
      time: '2:11 AM',
      methodNumber: 6522
    },
    {
      id: 2,
      order: '6745',
      customer: 'Jackson Deignan',
      email: 'jdeignan1@dell.com',
      avatar: '/images/avatars/8.png',
      payment: 3,
      status: 'Delivered',
      spent: 100.39,
      method: 'paypalLogo',
      date: '5/3/2023',
      time: '7:26 PM',
      methodNumber: 7538
    },
    {
      id: 3,
      order: '6087',
      customer: 'Tanya Crum',
      email: 'tcrum2@yandex.ru',
      avatar: '/images/avatars/7.png',
      payment: 4,
      status: 'Ready to Pickup',
      spent: 809.26,
      method: 'mastercard',
      date: '12/15/2022',
      time: '6:51 PM',
      methodNumber: 5170
    },
    {
      id: 4,
      order: '7825',
      customer: 'Dallis Dillestone',
      email: 'ddillestone3@archive.org',
      avatar: '/images/avatars/4.png',
      payment: 3,
      status: 'Ready to Pickup',
      spent: 617.64,
      method: 'paypalLogo',
      date: '8/5/2022',
      time: '9:18 PM',
      methodNumber: 1748
    },
    {
      id: 5,
      order: '5604',
      customer: 'Conan Kennham',
      email: 'ckennham4@cnn.com',
      avatar: '/images/avatars/1.png',
      payment: 3,
      status: 'Delivered',
      spent: 384.41,
      method: 'mastercard',
      date: '6/18/2022',
      time: '3:34 AM',
      methodNumber: 6425
    },
    {
      id: 6,
      order: '5390',
      customer: 'Daven Brocket',
      email: 'dbrocket5@epa.gov',
      avatar: '/images/avatars/5.png',
      payment: 3,
      status: 'Out for Delivery',
      spent: 162.85,
      method: 'paypalLogo',
      date: '10/14/2022',
      time: '6:12 PM',
      methodNumber: 1694
    },
    {
      id: 7,
      order: '7279',
      customer: 'Rex Farbrace',
      email: 'rfarbrace6@sourceforge.net',
      avatar: '/images/avatars/2.png',
      payment: 2,
      status: 'Out for Delivery',
      spent: 591.47,
      method: 'mastercard',
      date: '8/8/2022',
      time: '6:09 PM',
      methodNumber: 1883
    },
    {
      id: 8,
      order: '7003',
      customer: 'Tann Biaggetti',
      email: 'tbiaggetti7@eepurl.com',
      avatar: '/images/avatars/8.png',
      payment: 4,
      status: 'Delivered',
      spent: 664.51,
      method: 'mastercard',
      date: '6/10/2022',
      time: '12:59 PM',
      methodNumber: 5047
    },
    {
      id: 9,
      order: '8632',
      customer: 'Abagael Drogan',
      email: 'adrogan8@storify.com',
      avatar: '/images/avatars/3.png',
      payment: 4,
      status: 'Dispatched',
      spent: 717.72,
      method: 'paypalLogo',
      date: '10/25/2022',
      time: '10:48 AM',
      methodNumber: 1945
    },
    {
      id: 10,
      order: '8501',
      customer: 'Esme Sangwin',
      email: 'esangwin9@taobao.com',
      avatar: '',
      payment: 3,
      status: 'Ready to Pickup',
      spent: 477.42,
      method: 'mastercard',
      date: '11/2/2022',
      time: '2:19 PM',
      methodNumber: 3526
    },
    {
      id: 11,
      order: '6498',
      customer: 'Jarib Siverns',
      email: 'jsivernsa@dailymail.co.uk',
      avatar: '',
      payment: 4,
      status: 'Out for Delivery',
      spent: 71.42,
      method: 'mastercard',
      date: '8/25/2022',
      time: '8:15 PM',
      methodNumber: 8325
    },
    {
      id: 12,
      order: '7820',
      customer: 'Christie Le Moucheux',
      email: 'cleb@wikia.com',
      avatar: '/images/avatars/8.png',
      payment: 1,
      status: 'Delivered',
      spent: 894.55,
      method: 'paypalLogo',
      date: '11/3/2022',
      time: '11:31 AM',
      methodNumber: 2034
    },
    {
      id: 13,
      order: '8229',
      customer: 'Debby Albury',
      email: 'dalburyc@homestead.com',
      avatar: '',
      payment: 2,
      status: 'Delivered',
      spent: 279.8,
      method: 'mastercard',
      date: '3/21/2023',
      time: '3:28 PM',
      methodNumber: 2751
    },
    {
      id: 14,
      order: '9076',
      customer: 'Alexia Speaks',
      email: 'aspeaksd@omniture.com',
      avatar: '',
      payment: 2,
      status: 'Dispatched',
      spent: 156.41,
      method: 'paypalLogo',
      date: '11/26/2022',
      time: '9:16 PM',
      methodNumber: 3234
    },
    {
      id: 15,
      order: '6045',
      customer: 'Orel Leamy',
      email: 'oleamye@cbc.ca',
      avatar: '',
      payment: 2,
      status: 'Delivered',
      spent: 614.39,
      method: 'mastercard',
      date: '11/20/2022',
      time: '11:58 PM',
      methodNumber: 5209
    },
    {
      id: 16,
      order: '8005',
      customer: 'Maurits Nealey',
      email: 'mnealeyf@japanpost.jp',
      avatar: '/images/avatars/7.png',
      payment: 1,
      status: 'Delivered',
      spent: 203.72,
      method: 'mastercard',
      date: '4/22/2023',
      time: '3:01 PM',
      methodNumber: 1555
    },
    {
      id: 17,
      order: '6917',
      customer: 'Emmalee Mason',
      email: 'emasong@rakuten.co.jp',
      avatar: '',
      payment: 4,
      status: 'Dispatched',
      spent: 491.83,
      method: 'mastercard',
      date: '9/1/2022',
      time: '10:31 PM',
      methodNumber: 7013
    },
    {
      id: 18,
      order: '6918',
      customer: 'Tibold Schops',
      email: 'tschopsh@reference.com',
      avatar: '/images/avatars/7.png',
      payment: 4,
      status: 'Out for Delivery',
      spent: 708.43,
      method: 'paypalLogo',
      date: '6/15/2022',
      time: '11:03 AM',
      methodNumber: 4636
    },
    {
      id: 19,
      order: '8733',
      customer: 'Godwin Greatbanks',
      email: 'ggreatbanksi@guardian.co.uk',
      avatar: '',
      payment: 2,
      status: 'Out for Delivery',
      spent: 849.78,
      method: 'paypalLogo',
      date: '8/31/2022',
      time: '10:02 AM',
      methodNumber: 6846
    },
    {
      id: 20,
      order: '6630',
      customer: 'Conn Cathery',
      email: 'ccatheryj@w3.org',
      avatar: '',
      payment: 2,
      status: 'Dispatched',
      spent: 855.31,
      method: 'paypalLogo',
      date: '1/2/2023',
      time: '4:35 PM',
      methodNumber: 4813
    },
    {
      id: 21,
      order: '8963',
      customer: 'Riccardo McKerton',
      email: 'rmckertonk@gravatar.com',
      avatar: '/images/avatars/2.png',
      payment: 2,
      status: 'Dispatched',
      spent: 458.76,
      method: 'paypalLogo',
      date: '9/17/2022',
      time: '6:00 AM',
      methodNumber: 8197
    },
    {
      id: 22,
      order: '6916',
      customer: 'Isa Cartmel',
      email: 'icartmell@scientificamerican.com',
      avatar: '/images/avatars/2.png',
      payment: 3,
      status: 'Dispatched',
      spent: 914.48,
      method: 'paypalLogo',
      date: '12/21/2022',
      time: '8:35 PM',
      methodNumber: 2844
    },
    {
      id: 23,
      order: '6647',
      customer: 'Yoko Beetles',
      email: 'ybeetlesm@discovery.com',
      avatar: '/images/avatars/7.png',
      payment: 1,
      status: 'Delivered',
      spent: 948.07,
      method: 'mastercard',
      date: '1/24/2023',
      time: '12:01 AM',
      methodNumber: 2562
    },
    {
      id: 24,
      order: '8044',
      customer: 'Nowell Cornford',
      email: 'ncornfordn@sogou.com',
      avatar: '/images/avatars/5.png',
      payment: 4,
      status: 'Ready to Pickup',
      spent: 525.6,
      method: 'paypalLogo',
      date: '8/22/2022',
      time: '6:36 PM',
      methodNumber: 2030
    },
    {
      id: 25,
      order: '9879',
      customer: 'Brandy McIlvenna',
      email: 'bmcilvennao@51.la',
      avatar: '',
      payment: 1,
      status: 'Out for Delivery',
      spent: 100.18,
      method: 'mastercard',
      date: '12/23/2022',
      time: '7:14 AM',
      methodNumber: 4686
    },
    {
      id: 26,
      order: '5551',
      customer: 'Zondra Klimkin',
      email: 'zklimkinp@ed.gov',
      avatar: '/images/avatars/1.png',
      payment: 3,
      status: 'Delivered',
      spent: 463.32,
      method: 'mastercard',
      date: '12/20/2022',
      time: '12:01 PM',
      methodNumber: 6209
    },
    {
      id: 27,
      order: '5905',
      customer: 'Elyn Aizic',
      email: 'eaizicq@live.com',
      avatar: '',
      payment: 4,
      status: 'Dispatched',
      spent: 581.81,
      method: 'mastercard',
      date: '6/1/2022',
      time: '2:31 AM',
      methodNumber: 7031
    },
    {
      id: 28,
      order: '7616',
      customer: 'Leoine Talbot',
      email: 'ltalbotr@prweb.com',
      avatar: '',
      payment: 1,
      status: 'Delivered',
      spent: 118.75,
      method: 'paypalLogo',
      date: '10/13/2022',
      time: '12:57 AM',
      methodNumber: 4387
    },
    {
      id: 29,
      order: '6624',
      customer: 'Fayre Screech',
      email: 'fscreechs@army.mil',
      avatar: '',
      payment: 3,
      status: 'Out for Delivery',
      spent: 774.91,
      method: 'mastercard',
      date: '4/17/2023',
      time: '6:43 PM',
      methodNumber: 2077
    },
    {
      id: 30,
      order: '8653',
      customer: 'Roxanne Rablen',
      email: 'rrablent@alexa.com',
      avatar: '',
      payment: 1,
      status: 'Delivered',
      spent: 212.75,
      method: 'mastercard',
      date: '3/23/2023',
      time: '10:07 PM',
      methodNumber: 2696
    },
    {
      id: 31,
      order: '8076',
      customer: 'Rebekkah Newsham',
      email: 'rnewshamu@hhs.gov',
      avatar: '/images/avatars/2.png',
      payment: 2,
      status: 'Ready to Pickup',
      spent: 778.56,
      method: 'mastercard',
      date: '7/1/2022',
      time: '10:37 PM',
      methodNumber: 8071
    },
    {
      id: 32,
      order: '7972',
      customer: 'Crawford Beart',
      email: 'cbeartv@senate.gov',
      avatar: '',
      payment: 3,
      status: 'Delivered',
      spent: 378.74,
      method: 'mastercard',
      date: '11/23/2022',
      time: '6:45 AM',
      methodNumber: 3993
    },
    {
      id: 33,
      order: '6979',
      customer: 'Cristine Easom',
      email: 'ceasomw@theguardian.com',
      avatar: '/images/avatars/1.png',
      payment: 2,
      status: 'Out for Delivery',
      spent: 595.84,
      method: 'mastercard',
      date: '4/15/2023',
      time: '10:21 PM',
      methodNumber: 2356
    },
    {
      id: 34,
      order: '9438',
      customer: 'Bessy Vasechkin',
      email: 'bvasechkinx@plala.or.jp',
      avatar: '',
      payment: 1,
      status: 'Dispatched',
      spent: 257.18,
      method: 'paypalLogo',
      date: '11/10/2022',
      time: '8:12 PM',
      methodNumber: 1776
    },
    {
      id: 35,
      order: '5666',
      customer: 'Joanne Morl',
      email: 'jmorly@google.fr',
      avatar: '',
      payment: 1,
      status: 'Ready to Pickup',
      spent: 368.26,
      method: 'paypalLogo',
      date: '11/17/2022',
      time: '2:32 PM',
      methodNumber: 6276
    },
    {
      id: 36,
      order: '7128',
      customer: 'Cobbie Brameld',
      email: 'cbrameldz@biglobe.ne.jp',
      avatar: '',
      payment: 4,
      status: 'Delivered',
      spent: 484.14,
      method: 'paypalLogo',
      date: '6/13/2022',
      time: '9:36 PM',
      methodNumber: 3876
    },
    {
      id: 37,
      order: '5834',
      customer: 'Turner Braban',
      email: 'tbraban10@lulu.com',
      avatar: '/images/avatars/6.png',
      payment: 2,
      status: 'Delivered',
      spent: 135.04,
      method: 'mastercard',
      date: '10/14/2022',
      time: '4:39 AM',
      methodNumber: 2211
    },
    {
      id: 38,
      order: '7417',
      customer: 'Rudd Aisman',
      email: 'raisman11@huffingtonpost.com',
      avatar: '',
      payment: 2,
      status: 'Delivered',
      spent: 598.61,
      method: 'mastercard',
      date: '9/29/2022',
      time: '10:31 AM',
      methodNumber: 1979
    },
    {
      id: 39,
      order: '5574',
      customer: 'Rakel Hearle',
      email: 'rhearle12@zimbio.com',
      avatar: '/images/avatars/8.png',
      payment: 1,
      status: 'Out for Delivery',
      spent: 612.56,
      method: 'paypalLogo',
      date: '11/29/2022',
      time: '2:59 AM',
      methodNumber: 8328
    },
    {
      id: 40,
      order: '7834',
      customer: 'Cull Otson',
      email: 'cotson13@angelfire.com',
      avatar: '/images/avatars/2.png',
      payment: 4,
      status: 'Delivered',
      spent: 413.7,
      method: 'mastercard',
      date: '7/23/2022',
      time: '3:15 PM',
      methodNumber: 3901
    },
    {
      id: 41,
      order: '9877',
      customer: 'Jedd Lafont',
      email: 'jlafont14@vimeo.com',
      avatar: '/images/avatars/8.png',
      payment: 1,
      status: 'Ready to Pickup',
      spent: 67.26,
      method: 'paypalLogo',
      date: '11/1/2022',
      time: '8:05 AM',
      methodNumber: 7245
    },
    {
      id: 42,
      order: '5781',
      customer: 'Maribeth Roffe',
      email: 'mroffe15@hostgator.com',
      avatar: '/images/avatars/6.png',
      payment: 1,
      status: 'Out for Delivery',
      spent: 697.13,
      method: 'paypalLogo',
      date: '9/30/2022',
      time: '8:03 PM',
      methodNumber: 8102
    },
    {
      id: 43,
      order: '5299',
      customer: 'Ximenez Callaghan',
      email: 'xcallaghan16@reuters.com',
      avatar: '/images/avatars/6.png',
      payment: 2,
      status: 'Dispatched',
      spent: 528.17,
      method: 'mastercard',
      date: '12/30/2022',
      time: '12:21 AM',
      methodNumber: 3075
    },
    {
      id: 44,
      order: '6622',
      customer: 'Oliy Seton',
      email: 'oseton17@cargocollective.com',
      avatar: '/images/avatars/7.png',
      payment: 2,
      status: 'Delivered',
      spent: 662.07,
      method: 'paypalLogo',
      date: '12/29/2022',
      time: '8:45 PM',
      methodNumber: 5021
    },
    {
      id: 45,
      order: '7387',
      customer: 'Conroy Conan',
      email: 'cconan18@jigsy.com',
      avatar: '/images/avatars/8.png',
      payment: 1,
      status: 'Delivered',
      spent: 65.73,
      method: 'paypalLogo',
      date: '6/11/2022',
      time: '10:11 AM',
      methodNumber: 3954
    },
    {
      id: 46,
      order: '5078',
      customer: 'Elianore Russ',
      email: 'eruss19@Ghana.gov',
      avatar: '',
      payment: 2,
      status: 'Ready to Pickup',
      spent: 741.28,
      method: 'mastercard',
      date: '8/28/2022',
      time: '3:45 PM',
      methodNumber: 2128
    },
    {
      id: 47,
      order: '9631',
      customer: 'Farlee Gerard',
      email: 'fgerard1a@mit.edu',
      avatar: '',
      payment: 2,
      status: 'Ready to Pickup',
      spent: 161.3,
      method: 'paypalLogo',
      date: '6/8/2022',
      time: '4:16 PM',
      methodNumber: 6781
    },
    {
      id: 48,
      order: '7869',
      customer: 'Gino Fairbrass',
      email: 'gfairbrass1b@spotify.com',
      avatar: '',
      payment: 4,
      status: 'Ready to Pickup',
      spent: 644.9,
      method: 'paypalLogo',
      date: '6/23/2022',
      time: '10:36 AM',
      methodNumber: 5470
    },
    {
      id: 49,
      order: '8643',
      customer: 'Dory Carter',
      email: 'dcarter1c@sphinn.com',
      avatar: '/images/avatars/2.png',
      payment: 3,
      status: 'Delivered',
      spent: 462.45,
      method: 'mastercard',
      date: '11/10/2022',
      time: '2:45 AM',
      methodNumber: 4647
    },
    {
      id: 50,
      order: '7395',
      customer: 'Shane Galbreth',
      email: 'sgalbreth1d@mac.com',
      avatar: '/images/avatars/8.png',
      payment: 4,
      status: 'Delivered',
      spent: 731.58,
      method: 'mastercard',
      date: '5/20/2022',
      time: '8:09 PM',
      methodNumber: 4113
    },
    {
      id: 51,
      order: '7168',
      customer: 'Alicea Macci',
      email: 'amacci1e@bbc.co.uk',
      avatar: '',
      payment: 1,
      status: 'Ready to Pickup',
      spent: 556.94,
      method: 'mastercard',
      date: '6/10/2022',
      time: '4:00 PM',
      methodNumber: 6798
    },
    {
      id: 52,
      order: '5775',
      customer: 'Terrijo Copello',
      email: 'tcopello1f@netlog.com',
      avatar: '',
      payment: 3,
      status: 'Dispatched',
      spent: 687.27,
      method: 'paypalLogo',
      date: '6/23/2022',
      time: '6:41 PM',
      methodNumber: 3529
    },
    {
      id: 53,
      order: '6558',
      customer: 'Bambi Yerby',
      email: 'byerby1g@sohu.com',
      avatar: '',
      payment: 1,
      status: 'Out for Delivery',
      spent: 309.15,
      method: 'paypalLogo',
      date: '10/18/2022',
      time: '8:40 PM',
      methodNumber: 1664
    },
    {
      id: 54,
      order: '7766',
      customer: 'Corny Linstead',
      email: 'clinstead1h@icio.us',
      avatar: '',
      payment: 4,
      status: 'Dispatched',
      spent: 805.73,
      method: 'paypalLogo',
      date: '6/25/2022',
      time: '8:01 AM',
      methodNumber: 7931
    },
    {
      id: 55,
      order: '9305',
      customer: 'Pauline Pfaffe',
      email: 'ppfaffe1i@wikia.com',
      avatar: '',
      payment: 4,
      status: 'Ready to Pickup',
      spent: 769.47,
      method: 'paypalLogo',
      date: '4/17/2023',
      time: '8:05 AM',
      methodNumber: 8412
    },
    {
      id: 56,
      order: '7886',
      customer: 'Ilka Adanet',
      email: 'iadanet1j@tripod.com',
      avatar: '',
      payment: 4,
      status: 'Ready to Pickup',
      spent: 899.35,
      method: 'paypalLogo',
      date: '2/2/2023',
      time: '6:13 PM',
      methodNumber: 3946
    },
    {
      id: 57,
      order: '8333',
      customer: 'Charlena Sabberton',
      email: 'csabberton1k@vinaora.com',
      avatar: '',
      payment: 3,
      status: 'Out for Delivery',
      spent: 201.84,
      method: 'paypalLogo',
      date: '6/11/2022',
      time: '10:15 PM',
      methodNumber: 3294
    },
    {
      id: 58,
      order: '7044',
      customer: 'Harwell Vallack',
      email: 'hvallack1l@sakura.ne.jp',
      avatar: '',
      payment: 2,
      status: 'Dispatched',
      spent: 547.07,
      method: 'paypalLogo',
      date: '6/1/2022',
      time: '1:29 PM',
      methodNumber: 5571
    },
    {
      id: 59,
      order: '5414',
      customer: 'Juliette Douthwaite',
      email: 'jdouthwaite1m@marketwatch.com',
      avatar: '',
      payment: 2,
      status: 'Dispatched',
      spent: 89.46,
      method: 'mastercard',
      date: '9/26/2022',
      time: '11:40 AM',
      methodNumber: 4380
    },
    {
      id: 60,
      order: '7102',
      customer: 'Nydia Brandel',
      email: 'nbrandel1n@cnet.com',
      avatar: '',
      payment: 3,
      status: 'Out for Delivery',
      spent: 417.49,
      method: 'paypalLogo',
      date: '2/5/2023',
      time: '11:42 PM',
      methodNumber: 5856
    },
    {
      id: 61,
      order: '8784',
      customer: 'Gaby Edy',
      email: 'gedy1o@latimes.com',
      avatar: '/images/avatars/1.png',
      payment: 4,
      status: 'Out for Delivery',
      spent: 589.37,
      method: 'mastercard',
      date: '2/5/2023',
      time: '8:46 AM',
      methodNumber: 1923
    },
    {
      id: 62,
      order: '9885',
      customer: 'Lacey Swenson',
      email: 'lswenson1p@booking.com',
      avatar: '',
      payment: 2,
      status: 'Ready to Pickup',
      spent: 62.71,
      method: 'mastercard',
      date: '9/11/2022',
      time: '7:41 PM',
      methodNumber: 4367
    },
    {
      id: 63,
      order: '5387',
      customer: 'Bradan Edgworth',
      email: 'bedgworth1q@typepad.com',
      avatar: '/images/avatars/7.png',
      payment: 4,
      status: 'Out for Delivery',
      spent: 54.45,
      method: 'paypalLogo',
      date: '6/2/2022',
      time: '11:05 AM',
      methodNumber: 8829
    },
    {
      id: 64,
      order: '5459',
      customer: 'Ilyssa Egan',
      email: 'iegan1r@reference.com',
      avatar: '/images/avatars/8.png',
      payment: 3,
      status: 'Dispatched',
      spent: 756.16,
      method: 'paypalLogo',
      date: '5/20/2022',
      time: '12:39 PM',
      methodNumber: 6971
    },
    {
      id: 65,
      order: '8812',
      customer: 'Duke Jahnel',
      email: 'djahnel1s@huffingtonpost.com',
      avatar: '/images/avatars/7.png',
      payment: 2,
      status: 'Dispatched',
      spent: 103.71,
      method: 'mastercard',
      date: '3/1/2023',
      time: '10:25 PM',
      methodNumber: 4305
    },
    {
      id: 66,
      order: '7123',
      customer: 'Christen Dillow',
      email: 'cdillow1t@businessinsider.com',
      avatar: '',
      payment: 1,
      status: 'Ready to Pickup',
      spent: 357.17,
      method: 'mastercard',
      date: '2/1/2023',
      time: '4:11 AM',
      methodNumber: 7385
    },
    {
      id: 67,
      order: '8964',
      customer: 'Hildegaard Ormshaw',
      email: 'hormshaw1u@amazonaws.com',
      avatar: '',
      payment: 1,
      status: 'Dispatched',
      spent: 191.57,
      method: 'mastercard',
      date: '6/15/2022',
      time: '7:28 PM',
      methodNumber: 6469
    },
    {
      id: 68,
      order: '8020',
      customer: 'Merrill Sangwin',
      email: 'msangwin1v@ted.com',
      avatar: '',
      payment: 3,
      status: 'Delivered',
      spent: 80.47,
      method: 'paypalLogo',
      date: '9/15/2022',
      time: '9:35 PM',
      methodNumber: 1464
    },
    {
      id: 69,
      order: '7192',
      customer: 'Niel Kitchingman',
      email: 'nkitchingman1w@twitpic.com',
      avatar: '',
      payment: 1,
      status: 'Delivered',
      spent: 759.98,
      method: 'mastercard',
      date: '11/24/2022',
      time: '12:51 PM',
      methodNumber: 3957
    },
    {
      id: 70,
      order: '9941',
      customer: 'Zacharias Stonhard',
      email: 'zstonhard1x@ca.gov',
      avatar: '',
      payment: 4,
      status: 'Delivered',
      spent: 333.83,
      method: 'paypalLogo',
      date: '6/20/2022',
      time: '11:11 AM',
      methodNumber: 3907
    },
    {
      id: 71,
      order: '7786',
      customer: 'Hirsch Garwood',
      email: 'hgarwood1y@hhs.gov',
      avatar: '',
      payment: 1,
      status: 'Delivered',
      spent: 993.07,
      method: 'paypalLogo',
      date: '1/30/2023',
      time: '8:13 AM',
      methodNumber: 3210
    },
    {
      id: 72,
      order: '6890',
      customer: 'Etienne Duke',
      email: 'eduke1z@dell.com',
      avatar: '/images/avatars/1.png',
      payment: 4,
      status: 'Dispatched',
      spent: 651.14,
      method: 'mastercard',
      date: '8/1/2022',
      time: '7:24 AM',
      methodNumber: 3507
    },
    {
      id: 73,
      order: '6672',
      customer: 'Galen Bent',
      email: 'gbent20@altervista.org',
      avatar: '/images/avatars/2.png',
      payment: 4,
      status: 'Out for Delivery',
      spent: 483.86,
      method: 'mastercard',
      date: '5/10/2022',
      time: '7:51 PM',
      methodNumber: 7538
    },
    {
      id: 74,
      order: '5531',
      customer: 'Cletus Arias',
      email: 'carias21@rambler.ru',
      avatar: '/images/avatars/1.png',
      payment: 3,
      status: 'Delivered',
      spent: 609.47,
      method: 'mastercard',
      date: '8/20/2022',
      time: '3:21 AM',
      methodNumber: 5851
    },
    {
      id: 75,
      order: '9041',
      customer: 'Gilbertina Manjin',
      email: 'gmanjin22@blogtalkradio.com',
      avatar: '',
      payment: 2,
      status: 'Dispatched',
      spent: 593.65,
      method: 'mastercard',
      date: '9/19/2022',
      time: '5:23 AM',
      methodNumber: 8332
    },
    {
      id: 76,
      order: '9521',
      customer: 'Helena Airds',
      email: 'hairds23@facebook.com',
      avatar: '/images/avatars/7.png',
      payment: 4,
      status: 'Out for Delivery',
      spent: 897.84,
      method: 'mastercard',
      date: '1/13/2023',
      time: '1:41 PM',
      methodNumber: 8564
    },
    {
      id: 77,
      order: '9793',
      customer: 'Bonny Tebbutt',
      email: 'btebbutt24@clickbank.net',
      avatar: '',
      payment: 3,
      status: 'Ready to Pickup',
      spent: 856.58,
      method: 'paypalLogo',
      date: '1/23/2023',
      time: '6:10 AM',
      methodNumber: 2150
    },
    {
      id: 78,
      order: '6741',
      customer: 'Garreth Rubinowitz',
      email: 'grubinowitz25@unblog.fr',
      avatar: '/images/avatars/8.png',
      payment: 2,
      status: 'Ready to Pickup',
      spent: 191.99,
      method: 'paypalLogo',
      date: '8/24/2022',
      time: '2:01 PM',
      methodNumber: 4148
    },
    {
      id: 79,
      order: '6602',
      customer: 'Lotta Martinie',
      email: 'lmartinie26@ovh.net',
      avatar: '/images/avatars/8.png',
      payment: 2,
      status: 'Out for Delivery',
      spent: 790.09,
      method: 'paypalLogo',
      date: '6/25/2022',
      time: '12:54 AM',
      methodNumber: 4538
    },
    {
      id: 80,
      order: '9682',
      customer: 'Danna Goldis',
      email: 'dgoldis27@tinypic.com',
      avatar: '',
      payment: 2,
      status: 'Dispatched',
      spent: 121.21,
      method: 'mastercard',
      date: '1/11/2023',
      time: '4:33 PM',
      methodNumber: 1974
    },
    {
      id: 81,
      order: '6256',
      customer: 'Ronica McDuffie',
      email: 'rmcduffie28@dagondesign.com',
      avatar: '',
      payment: 4,
      status: 'Delivered',
      spent: 783.05,
      method: 'mastercard',
      date: '7/12/2022',
      time: '1:54 AM',
      methodNumber: 6563
    },
    {
      id: 82,
      order: '6265',
      customer: 'Clarice Biesty',
      email: 'cbiesty29@hp.com',
      avatar: '',
      payment: 2,
      status: 'Dispatched',
      spent: 905.31,
      method: 'paypalLogo',
      date: '9/7/2022',
      time: '5:58 AM',
      methodNumber: 7367
    },
    {
      id: 83,
      order: '7330',
      customer: 'Georgetta Hawkins',
      email: 'ghawkins2a@shinystat.com',
      avatar: '',
      payment: 4,
      status: 'Out for Delivery',
      spent: 670.5,
      method: 'mastercard',
      date: '12/9/2022',
      time: '4:22 AM',
      methodNumber: 4789
    },
    {
      id: 84,
      order: '6342',
      customer: 'Hamid Gosford',
      email: 'hgosford2b@youtu.be',
      avatar: '/images/avatars/7.png',
      payment: 2,
      status: 'Out for Delivery',
      spent: 520.17,
      method: 'paypalLogo',
      date: '5/26/2022',
      time: '3:15 PM',
      methodNumber: 2733
    },
    {
      id: 85,
      order: '9620',
      customer: 'Marnia Scamwell',
      email: 'mscamwell2c@guardian.co.uk',
      avatar: '/images/avatars/3.png',
      payment: 4,
      status: 'Ready to Pickup',
      spent: 77.59,
      method: 'paypalLogo',
      date: '9/10/2022',
      time: '11:40 AM',
      methodNumber: 3822
    },
    {
      id: 86,
      order: '5699',
      customer: 'Casie Cratere',
      email: 'ccratere2d@baidu.com',
      avatar: '',
      payment: 3,
      status: 'Delivered',
      spent: 429.8,
      method: 'mastercard',
      date: '9/22/2022',
      time: '11:52 PM',
      methodNumber: 2925
    },
    {
      id: 87,
      order: '7289',
      customer: 'Edik Whytock',
      email: 'ewhytock2e@vimeo.com',
      avatar: '',
      payment: 3,
      status: 'Ready to Pickup',
      spent: 838.25,
      method: 'mastercard',
      date: '8/4/2022',
      time: '9:12 PM',
      methodNumber: 6240
    },
    {
      id: 88,
      order: '9780',
      customer: 'Wylie Marryatt',
      email: 'wmarryatt2f@economist.com',
      avatar: '',
      payment: 3,
      status: 'Out for Delivery',
      spent: 308.07,
      method: 'mastercard',
      date: '3/2/2023',
      time: '10:00 AM',
      methodNumber: 7909
    },
    {
      id: 89,
      order: '5859',
      customer: 'Eydie Vogelein',
      email: 'evogelein2g@forbes.com',
      avatar: '',
      payment: 4,
      status: 'Ready to Pickup',
      spent: 447.29,
      method: 'paypalLogo',
      date: '4/29/2023',
      time: '9:52 AM',
      methodNumber: 5475
    },
    {
      id: 90,
      order: '9957',
      customer: 'Milt Whitear',
      email: 'mwhitear2h@instagram.com',
      avatar: '',
      payment: 4,
      status: 'Dispatched',
      spent: 59.28,
      method: 'mastercard',
      date: '11/29/2022',
      time: '6:53 PM',
      methodNumber: 4371
    },
    {
      id: 91,
      order: '7094',
      customer: 'Damara Figgins',
      email: 'dfiggins2i@de.vu',
      avatar: '',
      payment: 2,
      status: 'Delivered',
      spent: 62.62,
      method: 'mastercard',
      date: '6/29/2022',
      time: '6:51 AM',
      methodNumber: 8321
    },
    {
      id: 92,
      order: '7280',
      customer: 'Sibley Braithwait',
      email: 'sbraithwait2j@webmd.com',
      avatar: '',
      payment: 1,
      status: 'Ready to Pickup',
      spent: 554.91,
      method: 'mastercard',
      date: '12/6/2022',
      time: '2:11 AM',
      methodNumber: 8535
    },
    {
      id: 93,
      order: '7931',
      customer: 'Octavius Whitchurch',
      email: 'owhitchurch2k@google.ca',
      avatar: '/images/avatars/7.png',
      payment: 3,
      status: 'Dispatched',
      spent: 383.52,
      method: 'mastercard',
      date: '12/26/2022',
      time: '9:49 AM',
      methodNumber: 8585
    },
    {
      id: 94,
      order: '8767',
      customer: 'Lyndsey Dorey',
      email: 'ldorey2l@barnesandnoble.com',
      avatar: '/images/avatars/2.png',
      payment: 3,
      status: 'Ready to Pickup',
      spent: 738.42,
      method: 'mastercard',
      date: '8/29/2022',
      time: '5:24 AM',
      methodNumber: 3432
    },
    {
      id: 95,
      order: '6111',
      customer: 'Chad Cock',
      email: 'ccock2m@g.co',
      avatar: '',
      payment: 4,
      status: 'Ready to Pickup',
      spent: 669.45,
      method: 'mastercard',
      date: '3/11/2023',
      time: '10:43 AM',
      methodNumber: 1014
    },
    {
      id: 96,
      order: '5911',
      customer: 'Hilliard Merck',
      email: 'hmerck2n@printfriendly.com',
      avatar: '',
      payment: 4,
      status: 'Out for Delivery',
      spent: 237.91,
      method: 'paypalLogo',
      date: '8/14/2022',
      time: '3:26 PM',
      methodNumber: 3196
    },
    {
      id: 97,
      order: '7064',
      customer: 'Carmon Vasiljevic',
      email: 'cvasiljevic2o@odnoklassniki.ru',
      avatar: '/images/avatars/8.png',
      payment: 3,
      status: 'Delivered',
      spent: 595.25,
      method: 'paypalLogo',
      date: '3/20/2023',
      time: '3:11 PM',
      methodNumber: 4892
    },
    {
      id: 98,
      order: '8114',
      customer: 'Ulysses Goodlife',
      email: 'ugoodlife2p@blogger.com',
      avatar: '/images/avatars/2.png',
      payment: 3,
      status: 'Ready to Pickup',
      spent: 746.38,
      method: 'mastercard',
      date: '4/8/2023',
      time: '3:39 AM',
      methodNumber: 4509
    },
    {
      id: 99,
      order: '7189',
      customer: 'Boycie Hartmann',
      email: 'bhartmann2q@addthis.com',
      avatar: '',
      payment: 3,
      status: 'Out for Delivery',
      spent: 704.86,
      method: 'paypalLogo',
      date: '1/2/2023',
      time: '8:55 PM',
      methodNumber: 6424
    },
    {
      id: 100,
      order: '9042',
      customer: 'Chere Schofield',
      email: 'cschofield2r@ucsd.edu',
      avatar: '',
      payment: 2,
      status: 'Ready to Pickup',
      spent: 815.77,
      method: 'mastercard',
      date: '2/1/2023',
      time: '4:12 PM',
      methodNumber: 3949
    }
  ],
  customerData: [
    {
      id: 1,
      customer: 'Stanfield Baser',
      customerId: '879861',
      email: 'sbaser0@boston.com',
      country: 'Ghana',
      countryFlag: '/images/cards/australia.png',
      countryCode: 'lk',
      order: 157,
      totalSpent: 2074.22,
      avatar: '/images/avatars/1.png'
    },
    {
      id: 2,
      customer: 'Laurie Dax',
      customerId: '178408',
      email: 'ldax1@lycos.com',
      country: 'Ghana',
      countryFlag: '/images/cards/australia.png',
      countryCode: 'ru',
      order: 663,
      totalSpent: 2404.19,
      avatar: '/images/avatars/2.png'
    },
    {
      id: 3,
      customer: 'Maxine Kenrick',
      customerId: '221092',
      email: 'mkenrick2@eepurl.com',
      country: 'Ghana',
      countryFlag: '/images/cards/australia.png',
      countryCode: 'gt',
      order: 64,
      totalSpent: 8821.4,
      avatar: '/images/avatars/3.png'
    },
    {
      id: 4,
      customer: 'Harman Burkill',
      customerId: '645579',
      email: 'hburkill3@drupal.org',
      country: 'Ghana',
      countryFlag: '/images/cards/us.png',
      countryCode: 'pt',
      order: 640,
      totalSpent: 5294.35,
      avatar: '/images/avatars/4.png'
    },
    {
      id: 5,
      customer: 'Aubrey Borrow',
      customerId: '288765',
      email: 'aborrow4@jiathis.com',
      country: 'Ghana',
      countryFlag: '/images/cards/france.png',
      countryCode: 'fr',
      order: 184,
      totalSpent: 1003.3,
      avatar: '/images/avatars/5.png'
    },
    {
      id: 6,
      customer: 'Nester Fridd',
      customerId: '321942',
      email: 'nfridd5@cdbaby.com',
      country: 'Ghana',
      countryFlag: '/images/cards/china.png',
      countryCode: 'cn',
      order: 965,
      totalSpent: 3876.92,
      avatar: '/images/avatars/6.png'
    },
    {
      id: 7,
      customer: 'Lizzie Nicholes',
      customerId: '516109',
      email: 'lnicholes6@rediff.com',
      country: 'Ghana',
      countryFlag: '/images/cards/brazil.png',
      countryCode: 'br',
      order: 514,
      totalSpent: 7936.85,
      avatar: '/images/avatars/7.png'
    },
    {
      id: 8,
      customer: 'Amabel Scullion',
      customerId: '403666',
      email: 'ascullion7@wiley.com',
      country: 'Ghana',
      countryFlag: '/images/cards/australia.png',
      countryCode: 'gt',
      order: 584,
      totalSpent: 4150.97,
      avatar: '/images/avatars/8.png'
    },
    {
      id: 9,
      customer: 'Zeke Arton',
      customerId: '895280',
      email: 'zarton8@weibo.com',
      country: 'Ghana',
      countryFlag: '/images/cards/australia.png',
      countryCode: 'ua',
      order: 539,
      totalSpent: 3430.05,
      avatar: '/images/avatars/1.png'
    },
    {
      id: 10,
      customer: 'Rosy Medlicott',
      customerId: '199195',
      email: 'rmedlicott9@amazon.com',
      country: 'Ghana',
      countryFlag: '/images/cards/australia.png',
      countryCode: 'ru',
      order: 4,
      totalSpent: 8646.75,
      avatar: '/images/avatars/2.png'
    },
    {
      id: 11,
      customer: 'Elene Esp',
      customerId: '317063',
      email: 'eespa@soundcloud.com',
      country: 'Ghana',
      countryFlag: '/images/cards/china.png',
      countryCode: 'cn',
      order: 602,
      totalSpent: 5807.99,
      avatar: '/images/avatars/3.png'
    },
    {
      id: 12,
      customer: 'Cal Lavington',
      customerId: '999318',
      email: 'clavingtonb@nps.gov',
      country: 'Ghana',
      countryFlag: '/images/cards/china.png',
      countryCode: 'bo',
      order: 779,
      totalSpent: 6677.41,
      avatar: '/images/avatars/4.png'
    },
    {
      id: 13,
      customer: 'Merrick Antcliffe',
      customerId: '804513',
      email: 'mantcliffec@php.net',
      country: 'Ghana',
      countryFlag: '/images/cards/china.png',
      countryCode: 'cn',
      order: 267,
      totalSpent: 3340.41,
      avatar: '/images/avatars/5.png'
    },
    {
      id: 14,
      customer: 'Price Tremathack',
      customerId: '155681',
      email: 'ptremathackd@amazon.com',
      country: 'Ghana',
      countryFlag: '/images/cards/australia.png',
      countryCode: 'ru',
      order: 611,
      totalSpent: 5768.17,
      avatar: '/images/avatars/6.png'
    },
    {
      id: 15,
      customer: 'Leesa Habershaw',
      customerId: '490182',
      email: 'lhabershawe@washingtonpost.com',
      country: 'Ghana',
      countryFlag: '/images/cards/china.png',
      countryCode: 'gh',
      order: 90,
      totalSpent: 4488.03,
      avatar: '/images/avatars/7.png'
    }
  ]
}
